# Generated by Django 6.0.6 on 2026-07-20 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0001_initial'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.torneo'),
        ),
    ]
