# Generated by Django 6.0.6 on 2026-07-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_initial'),
        ('torneos', '0003_torneo_equipos_por_jornada_torneo_fase_grupos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='torneo',
        ),
        migrations.AddField(
            model_name='partido',
            name='categoria',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.categoria'),
            preserve_default=False,
        ),
    ]
