# Generated by Django 6.0.6 on 2026-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_remove_partido_torneo_partido_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora'),
        ),
    ]
