# Generated by Django 6.0.6 on 2026-07-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0005_alter_partido_options_partido_ganador_penales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fecha_original',
            field=models.DateTimeField(blank=True, help_text='Se guarda la primera vez que se programa. Si despues cambia, el partido figura reprogramado.', null=True, verbose_name='Fecha asignada al principio'),
        ),
    ]
