# Generated by Django 6.0.6 on 2026-07-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0011_partido_siembra_local_partido_siembra_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='penales_local',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Penales del local'),
        ),
        migrations.AddField(
            model_name='partido',
            name='penales_visitante',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Penales del visitante'),
        ),
    ]
