# Generated by Django 6.0.6 on 2026-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0013_partido_vuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacion',
            name='goles_de_penal',
            field=models.PositiveIntegerField(default=0, help_text='Cuantos de sus goles fueron desde el punto penal. Es un subconjunto de "Goles", no se suma aparte.', verbose_name='De penal'),
        ),
    ]
