# Generated by Django 6.0.7 on 2026-08-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_equipo_jornada_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B')], default='', help_text='Solo en los torneos que se juegan por grupos.', max_length=1, verbose_name='Grupo'),
        ),
    ]
