# Generated by Django 6.0.7 on 2026-08-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_equipo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H'), ('I', 'Grupo I'), ('J', 'Grupo J'), ('K', 'Grupo K'), ('L', 'Grupo L'), ('M', 'Grupo M'), ('N', 'Grupo N'), ('O', 'Grupo O'), ('P', 'Grupo P'), ('Q', 'Grupo Q'), ('R', 'Grupo R'), ('S', 'Grupo S'), ('T', 'Grupo T'), ('U', 'Grupo U'), ('V', 'Grupo V'), ('W', 'Grupo W'), ('X', 'Grupo X'), ('Y', 'Grupo Y'), ('Z', 'Grupo Z')], default='', help_text='Solo en las categorías de torneo que se juegan por grupos.', max_length=1, verbose_name='Grupo'),
        ),
    ]
