# Generated by Django 6.0.7 on 2026-08-24 18:17

from django.conf import settings
from django.db import migrations, models

from apps.usuarios.rutas import apodo_libre


def llenar(apps, schema_editor):
    Equipo = apps.get_model('equipos', 'Equipo')
    por_categoria = {}
    for equipo in Equipo.objects.all().order_by('pk'):
        hermanos = por_categoria.setdefault(equipo.categoria_id, set())
        equipo.slug = apodo_libre(equipo.nombre, hermanos)
        hermanos.add(equipo.slug)
        equipo.save(update_fields=['slug'])


def vaciar(apps, schema_editor):
    apps.get_model('equipos', 'Equipo').objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_alter_equipo_grupo'),
        ('torneos', '0021_categoria_slug_liga_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Nombre en la dirección'),
        ),
        migrations.RunPython(llenar, vaciar),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('categoria', 'slug'), name='equipo_slug_unico_por_categoria'),
        ),
    ]
