# Generated by Django 6.0.7 on 2026-09-11 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_equipo_slug_equipo_equipo_slug_unico_por_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='titulos_campeon',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Veces campeón'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='titulos_subcampeon',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Veces subcampeón'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='titulos_tercero',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Veces tercer lugar'),
        ),
    ]
