# Generated by Django 6.0.7 on 2026-09-17 17:22

import apps.equipos.redes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0011_equipo_titulos_campeon_equipo_titulos_subcampeon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='red_facebook',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('Facebook', ('facebook.com', 'fb.com'))], verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='red_instagram',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('Instagram', ('instagram.com',))], verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='red_tiktok',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('TikTok', ('tiktok.com',))], verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='red_twitter',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('X (antes Twitter)', ('x.com', 'twitter.com'))], verbose_name='X (antes Twitter)'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H'), ('I', 'Grupo I'), ('J', 'Grupo J'), ('K', 'Grupo K'), ('L', 'Grupo L'), ('M', 'Grupo M'), ('N', 'Grupo N'), ('O', 'Grupo O'), ('P', 'Grupo P'), ('Q', 'Grupo Q'), ('R', 'Grupo R'), ('S', 'Grupo S'), ('T', 'Grupo T'), ('U', 'Grupo U'), ('V', 'Grupo V'), ('W', 'Grupo W'), ('X', 'Grupo X'), ('Y', 'Grupo Y'), ('Z', 'Grupo Z')], default='', help_text='Solo en las categorías que se juegan por grupos.', max_length=1, verbose_name='Grupo'),
        ),
    ]
