"""
Django settings for futbol project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config
from django.utils.csp import CSP

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,192.168.100.37,testserver',
    cast=Csv(),
)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_ESQUEMA_ORIGINAL', 'https')

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

COOKIES_SEGURAS = config('COOKIES_SEGURAS', default=False, cast=bool)
SESSION_COOKIE_SECURE = COOKIES_SEGURAS
CSRF_COOKIE_SECURE = COOKIES_SEGURAS

FORZAR_HTTPS = config('FORZAR_HTTPS', default=False, cast=bool)
SECURE_SSL_REDIRECT = FORZAR_HTTPS

SECURE_REDIRECT_EXEMPT = [r'^\.well-known/acme-challenge/']

SESSION_COOKIE_AGE = config('SESION_MINUTOS', default=20, cast=int) * 60

SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = config(
    'SESION_CIERRA_CON_NAVEGADOR', default=True, cast=bool
)

SESION_AVISO_SEGUNDOS = config('SESION_AVISO_SEGUNDOS', default=120, cast=int)

SECURE_CSP_REPORT_ONLY = {
    'default-src': [CSP.SELF],
    'script-src': [CSP.SELF],
    'style-src': [CSP.SELF, CSP.UNSAFE_INLINE],
    'img-src': [CSP.SELF, 'data:', 'https://*.tile.openstreetmap.org'],
    'connect-src': [CSP.SELF, 'https://nominatim.openstreetmap.org'],
    'frame-ancestors': [CSP.NONE],
    'base-uri': [CSP.SELF],
    'object-src': [CSP.NONE],
    'form-action': [CSP.SELF],
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django.forms',

    'axes',
    'apps.usuarios',
    'apps.torneos',
    'apps.equipos',
    'apps.jugadores',
    'apps.partidos',
    'apps.estadisticas',
    'apps.informacion',
]

MIDDLEWARE = [
    'futbol.middleware.NoCacheEnDesarrolloMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

if DEBUG:
    INSTALLED_APPS.append('django_browser_reload')
    MIDDLEWARE.insert(0, 'django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'futbol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'futbol.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='SISTEMA-FUTBOL'),
        'USER': config('DB_USER', default='sistema_user'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

AUTH_USER_MODEL = 'usuarios.Usuario'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', default=5, cast=int)

AXES_COOLOFF_TIME = config('AXES_COOLOFF_HORAS', default=0.25, cast=float)

AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]

AXES_CLIENT_IP_CALLABLE = 'apps.usuarios.auditoria.ip_de'

AXES_RESET_ON_SUCCESS = True

AXES_LOCKOUT_TEMPLATE = 'usuarios/bloqueado.html'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default='') or str(BASE_DIR / 'media')

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'


LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/usuarios/dashboard/'
LOGOUT_REDIRECT_URL = '/usuarios/login/'


CARPETA_LOGS = Path(config('CARPETA_LOGS', default='') or (BASE_DIR / 'logs'))
CARPETA_LOGS.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detallado': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'archivo_seguridad': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': CARPETA_LOGS / 'seguridad.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'detallado',
            'encoding': 'utf-8',
        },
        'archivo_errores': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': CARPETA_LOGS / 'errores.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'detallado',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['archivo_seguridad'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['archivo_errores'],
            'level': 'ERROR',
            'propagate': False,
        },
        'axes': {
            'handlers': ['archivo_seguridad'],
            'level': 'INFO',
            'propagate': False,
        },
        'futbol.auditoria': {
            'handlers': ['archivo_seguridad'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
