"""
Django settings for futbol project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Sin `default` a proposito: es un secreto y no puede vivir en el codigo, que si
# se versiona. Si falta en el .env el arranque revienta con UndefinedValueError,
# que es lo que se busca: mejor no arrancar que arrancar con una clave conocida
# —con ella se firman las sesiones, asi que se podrian falsificar.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,192.168.100.37,testserver',
    cast=Csv(),
)

# IIS termina el TLS y reenvia por HTTP simple a Waitress (ver web.config,
# ReverseProxyInboundRule1). Sin esto Django cree que toda peticion es HTTP,
# lo que rompe la verificacion de CSRF cuando se entra por HTTPS (el Origin
# que manda el navegador es https:// pero Django arma http:// para comparar).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Marca las cookies de sesion y de CSRF como "solo por HTTPS": asi el navegador
# se niega a mandarlas si alguien entra por http:// sin la ese. Sin esto, esa
# visita manda el identificador de sesion en claro y quien comparta la red se
# queda con ella sin necesitar la contrasena.
#
# Sale del .env y no de DEBUG para no diferenciar entornos en el codigo: en
# produccion va True, y en desarrollo False, porque ahi se entra por http://
# localhost y con True el login no guardaria la sesion —seria imposible entrar.
COOKIES_SEGURAS = config('COOKIES_SEGURAS', default=False, cast=bool)
SESSION_COOKIE_SECURE = COOKIES_SEGURAS
CSRF_COOKIE_SECURE = COOKIES_SEGURAS

# Manda a https:// a quien entre por http://. El puerto 80 esta abierto, asi que
# sin esto el sitio se sirve igual en texto plano: las cookies marcadas arriba
# no viajarian, pero el usuario y la contrasena que se escriben en el formulario
# de login si, porque van en el cuerpo del POST.
#
# Depende de que el proxy avise por que esquema entro la peticion original (ver
# SECURE_PROXY_SSL_HEADER arriba). El web.config de IIS lo manda —regla
# ReverseProxyInboundRule1, variable HTTP_X_FORWARDED_PROTO—; si eso se rompiera,
# Django creeria que toda peticion es HTTP y redirigiria en bucle. Por eso sale
# del .env: se apaga sin tocar el codigo ni volver a desplegar.
FORZAR_HTTPS = config('FORZAR_HTTPS', default=False, cast=bool)
SECURE_SSL_REDIRECT = FORZAR_HTTPS

# El desafio de Let's Encrypt tiene que poder responderse por http:// simple.
# Hoy no llega hasta aca —IIS lo sirve del disco antes, ver web.config—, pero si
# esa regla se perdiera en un cambio futuro, sin esta excepcion la renovacion del
# certificado empezaria a fallar sin que nadie se entere hasta que vence.
SECURE_REDIRECT_EXEMPT = [r'^\.well-known/acme-challenge/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Habilita el lookup __unaccent, para buscar sin importar acentos ni ñ.
    'django.contrib.postgres',
    # Permite reemplazar plantillas de widgets desde templates/django/forms/.
    'django.forms',

    'django_browser_reload',
    # Cuenta los intentos fallidos de login y bloquea al que insiste. Sin esto
    # se pueden probar contrasenas sin limite: el sitio esta en internet y una
    # cuenta con clave floja cae sola con tiempo.
    'axes',
    # Apps del proyecto
    'apps.usuarios',
    'apps.torneos',
    'apps.equipos',
    'apps.jugadores',
    'apps.partidos',
    'apps.estadisticas',
    'apps.informacion',
]

MIDDLEWARE = [
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    # Solo actua con DEBUG=True; con DEBUG=False Django lo descarta al arrancar.
    'futbol.middleware.NoCacheEnDesarrolloMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Va al final y despues de AuthenticationMiddleware: necesita request.user
    # ya resuelto para poder anotar quien fallo el intento.
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'futbol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Hace que los widgets de formulario se busquen tambien en templates/, para
# poder reemplazar el de subida de archivos por uno con mejor presentacion.
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'futbol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='SISTEMA-FUTBOL'),
        'USER': config('DB_USER', default='sistema_user'),
        # Sin `default`, igual que SECRET_KEY: la contrasena de la base es un
        # secreto y el default quedaba escrito en un archivo versionado. Ademas,
        # si faltaba la variable el proyecto arrancaba igual contra esa clave en
        # vez de avisar. Nombre, host y puerto si conservan default: no son
        # secretos y dejan que un clon nuevo levante sin configurar nada.
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

AUTH_USER_MODEL = 'usuarios.Usuario'

# Axes tiene que ir PRIMERO: es el que corta el intento cuando la cuenta esta
# bloqueada, antes de que el backend de siempre se ponga a comparar el hash.
# Si fuera segundo, el bloqueo no serviria de nada.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Cuantos intentos fallidos se toleran antes de bloquear.
AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', default=5, cast=int)

# Cuanto dura el bloqueo, en horas. Se cuenta desde el ultimo intento fallido.
# Un cuarto de hora frena de sobra un ataque automatizado —que necesita miles
# de intentos por minuto para servir de algo— sin dejar afuera media tarde a
# quien simplemente se equivoco de contrasena.
AXES_COOLOFF_TIME = config('AXES_COOLOFF_HORAS', default=0.25, cast=float)

# Se bloquea la combinacion usuario+IP, no el usuario solo ni la IP sola.
# Solo el usuario dejaria que cualquiera bloquee la cuenta del administrador
# fallando aposta cinco veces. Solo la IP dejaria afuera a toda una liga que
# comparte la conexion del club porque uno se equivoco.
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# Entrar bien borra los fallos acumulados: si alguien se equivoco tres veces y
# a la cuarta acerto, no tiene por que arrastrar el contador.
AXES_RESET_ON_SUCCESS = True

# Lo que ve quien queda bloqueado. Sin esto Axes devuelve un 403 pelado, que no
# le explica nada a un entrenador que solo se equivoco de contrasena.
AXES_LOCKOUT_TEMPLATE = 'usuarios/bloqueado.html'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
# Carpeta donde se guardan las imagenes que suben los usuarios (escudos, logos
# y fotos). Se define en el .env para que apunte a un lugar distinto en cada
# maquina sin tocar el codigo, y sobre todo para que en el servidor quede fuera
# del proyecto: si estuviera adentro, un despliegue la borraria con todo.
# Sin la variable usa media/ dentro del proyecto, para que un clon nuevo ande.
MEDIA_ROOT = config('MEDIA_ROOT', default=str(BASE_DIR / 'media'))

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'


LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/usuarios/dashboard/'
LOGOUT_REDIRECT_URL = '/usuarios/login/'
