# Generated by Django 6.0.7 on 2026-09-18 15:25

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatrocinadorOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre del patrocinador')),
                ('logo', models.ImageField(blank=True, help_text='Opcional. Si lo dejas vacío se muestran sus iniciales.', null=True, upload_to='aliados-oficiales/', verbose_name='Logo')),
                ('giro', models.CharField(blank=True, help_text='Taquería, refaccionaria, farmacia… Se muestra en su ficha.', max_length=120, verbose_name='Giro o actividad')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('telefono', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos, sin letras ni signos.')], verbose_name='Teléfono')),
                ('enlace', models.URLField(blank=True, help_text='Opcional. Aparece como un botón dentro de su ficha.', max_length=300, verbose_name='Sitio web o red social')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para esconderlo sin perder sus datos.', verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Patrocinador oficial',
                'verbose_name_plural': 'Patrocinadores oficiales',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='patrocinador_oficial_nombre_unico', violation_error_message='Ya hay un patrocinador oficial con ese nombre.')],
            },
        ),
    ]
