# Generated by Django 6.0.6 on 2026-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_fix_staff_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Administrador General'), ('adminliga', 'Administrador de Liga'), ('entrenador', 'Entrenador')], default='entrenador', help_text='Rol principal dentro del sistema deportivo.', max_length=20),
        ),
    ]
