# Generated by Django 6.0.6 on 2026-07-28 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_limite_ligas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos, sin letras ni signos.')], verbose_name='Teléfono'),
        ),
    ]
