# Generated by Django 6.0.6 on 2026-07-28 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Qué administrador creó esta cuenta. Define quién puede verla y editarla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Dado de alta por'),
        ),
    ]
