# Generated by Django 6.0.6 on 2026-07-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_jugador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='activo',
        ),
    ]
