# Generated by Django 6.0.6 on 2026-07-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_alter_equipo_entrenador'),
        ('jugadores', '0004_remove_jugador_activo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('equipo', 'numero'), name='dorsal_unico_por_equipo', violation_error_message='Ese número ya lo tiene otro jugador del equipo.'),
        ),
    ]
