# Generated by Django 6.0.6 on 2026-08-06 15:09
#
# Los 2 832 jugadores que ya estaban cargados quedan en 'masculino' por el
# default del campo. Se eligio ese y no dejarlos vacios porque es el limite
# estricto: una jugadora mal marcada pierde el año de tolerancia y el sistema la
# rechaza con un mensaje que dice como arreglarlo, mientras que al reves habria
# dejado entrar varones de mas edad sin que nadie se entere.
#
# Antes de correr esto se reviso la base: la liga real (Villahermosa) tenia 12
# jugadores y el resto son ligas de prueba con nombres generados.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_jugador_dorsal_unico_por_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', help_text='Define el límite de edad: las mujeres entran con un año más que la categoría.', max_length=10, verbose_name='Sexo'),
        ),
    ]
