# Generated by Django 6.0.6 on 2026-07-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='equipos_por_jornada',
            field=models.PositiveIntegerField(default=2, verbose_name='Equipos por jornada'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase_grupos',
            field=models.BooleanField(default=False, verbose_name='Incluye fase de grupos'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='formato',
            field=models.CharField(choices=[('liga', 'Liga'), ('grupos', 'Fase de grupos'), ('eliminatorio', 'Eliminatorio')], default='liga', max_length=20, verbose_name='Formato de competencia'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='inscripcion_abierta',
            field=models.BooleanField(default=True, verbose_name='Inscripción abierta'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='reglas',
            field=models.TextField(blank=True, verbose_name='Reglas del torneo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='tiene_playoffs',
            field=models.BooleanField(default=False, verbose_name='Incluye playoffs'),
        ),
    ]
