# Generated by Django 6.0.6 on 2026-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0006_categoria_rango_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_nacimiento_desde',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_nacimiento_hasta',
        ),
        migrations.AddField(
            model_name='categoria',
            name='limite_edad',
            field=models.CharField(blank=True, choices=[('U5', 'U5'), ('U7', 'U7'), ('U9', 'U9'), ('U11', 'U11'), ('U13', 'U13'), ('U15', 'U15'), ('U17', 'U17')], help_text='U9 entra un jugador de 9 años o menos, no uno de 10.', max_length=4, verbose_name='Límite de edad'),
        ),
    ]
