# Generated by Django 6.0.6 on 2026-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0010_categoria_cerrada_categoria_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='portada',
            field=models.ImageField(blank=True, help_text='Opcional. Se muestra de fondo en las pantallas de esta liga horizontal.', null=True, upload_to='portadas-ligas/', verbose_name='Portada de la liga'),
        ),
    ]
