# Generated by Django 6.0.7 on 2026-08-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0018_palmares_es_torneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='formato',
            field=models.CharField(choices=[('directa', 'Eliminación directa'), ('grupos', 'Round robin en dos grupos')], default='directa', max_length=20, verbose_name='Formato'),
        ),
    ]
