# Generated by Django 6.0.7 on 2026-08-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0019_torneo_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='grupos',
            field=models.PositiveSmallIntegerField(default=0, help_text='En cuántos grupos se reparten los equipos. Cero es sin grupos.', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha',
            field=models.DateField(help_text='En eliminación directa se juega entero ese día. Por grupos es la fecha de arranque: cada partido lleva la suya.', verbose_name='Día del torneo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='formato',
            field=models.CharField(choices=[('directa', 'Eliminación directa'), ('grupos', 'Por categorías y grupos')], default='directa', max_length=20, verbose_name='Formato'),
        ),
    ]
