# Generated by Django 6.0.7 on 2026-08-24 18:17

from django.conf import settings
from django.db import migrations, models

from apps.usuarios.rutas import apodo_libre


def llenar(apps, schema_editor):
    Liga = apps.get_model('torneos', 'Liga')
    Categoria = apps.get_model('torneos', 'Categoria')

    ocupados = set()
    for liga in Liga.objects.all().order_by('pk'):
        liga.slug = apodo_libre(liga.nombre, ocupados)
        ocupados.add(liga.slug)
        liga.save(update_fields=['slug'])

    por_liga = {}
    for categoria in Categoria.objects.all().order_by('pk'):
        hermanas = por_liga.setdefault(categoria.liga_id, set())
        categoria.slug = apodo_libre(categoria.nombre, hermanas)
        hermanas.add(categoria.slug)
        categoria.save(update_fields=['slug'])


def vaciar(apps, schema_editor):
    apps.get_model('torneos', 'Liga').objects.update(slug='')
    apps.get_model('torneos', 'Categoria').objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0020_categoria_grupos_alter_torneo_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Nombre en la dirección'),
        ),
        migrations.AddField(
            model_name='liga',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Nombre en la dirección'),
        ),
        migrations.RunPython(llenar, vaciar),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('liga', 'slug'), name='categoria_slug_unico_por_liga'),
        ),
        migrations.AddConstraint(
            model_name='liga',
            constraint=models.UniqueConstraint(fields=('slug',), name='liga_slug_unico'),
        ),
    ]
