# Generated by Django 6.0.7 on 2026-08-27 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0021_categoria_slug_liga_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre del patrocinador')),
                ('logo', models.ImageField(blank=True, help_text='Opcional. Si lo dejas vacío se muestran sus iniciales.', null=True, upload_to='patrocinadores/', verbose_name='Logo')),
                ('giro', models.CharField(blank=True, help_text='Taquería, refaccionaria, farmacia… Se muestra debajo del nombre.', max_length=120, verbose_name='Giro o actividad')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('telefono', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos, sin letras ni signos.')], verbose_name='Teléfono')),
                ('enlace', models.URLField(blank=True, help_text='Opcional. Aparece como un botón dentro de su ficha.', max_length=300, verbose_name='Sitio web o red social')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Los más chicos se muestran primero. Con el mismo número manda el nombre.', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para esconderlo sin perder sus datos.', verbose_name='Visible')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrocinadores', to='torneos.liga')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('liga', 'nombre'), name='patrocinador_unico_por_liga', violation_error_message='Esa liga ya tiene un patrocinador con ese nombre.')],
            },
        ),
    ]
