# Generated by Django 6.0.7 on 2026-08-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0022_patrocinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='logo',
            field=models.ImageField(blank=True, help_text='Opcional. Si lo dejas vacío se muestran sus iniciales.', null=True, upload_to='aliados/', verbose_name='Logo'),
        ),
    ]
