# Generated by Django 6.0.7 on 2026-09-10 18:23

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0023_alter_patrocinador_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='Trofeo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='trofeos/', verbose_name='Imagen del trofeo')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trofeos', to='torneos.liga')),
            ],
            options={
                'verbose_name': 'Trofeo',
                'verbose_name_plural': 'Trofeos',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('liga', 'titulo'), name='trofeo_unico_por_liga', violation_error_message='Ya cargaste un trofeo con ese nombre.')],
            },
        ),
    ]
