# Generated by Django 6.0.7 on 2026-09-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0024_trofeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cruces_entre_grupos',
            field=models.BooleanField(default=False, help_text='Solo aplica a los grupos con una cantidad impar de equipos. Evita que alguien se quede sin jugar, pero deja las tablas con distinta cantidad de partidos jugados.', verbose_name='Los que descansan juegan contra otro grupo'),
        ),
    ]
