# Generated by Django 6.0.7 on 2026-09-17 18:06

import apps.equipos.redes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0025_cruces_entre_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='red_facebook',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('Facebook', ('facebook.com', 'fb.com'))], verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='liga',
            name='red_instagram',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('Instagram', ('instagram.com',))], verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='liga',
            name='red_tiktok',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('TikTok', ('tiktok.com',))], verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='liga',
            name='red_twitter',
            field=models.URLField(blank=True, max_length=300, validators=[apps.equipos.redes.EnlaceDeRed('X (antes Twitter)', ('x.com', 'twitter.com'))], verbose_name='X (antes Twitter)'),
        ),
    ]
